---
- block:
  - name: Install fonts
    pacman:
      name:
        - ttf-font-awesome
        - ttf-firacode-nerd
        - ttf-iosevka-nerd
        - noto-fonts-emoji
      state: present
  become: true